use anyhow::{anyhow, Result};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::fs;
use std::path::PathBuf;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Config {
    pub default_base_branch: String,
    pub auto_push: bool,
    pub draft_prs: bool,
    pub pr_template: Option<String>,
    #[serde(default)]
    pub user_settings: HashMap<String, String>,
}

impl Default for Config {
    fn default() -> Self {
        Config {
            default_base_branch: "main".to_string(),
            auto_push: true,
            draft_prs: false,
            pr_template: None,
            user_settings: HashMap::new(),
        }
    }
}

impl Config {
    pub fn load() -> Result<Self> {
        let config_path = get_config_path()?;

        if config_path.exists() {
            let content = fs::read_to_string(&config_path)?;
            let config: Config = toml::from_str(&content)?;
            Ok(config)
        } else {
            Ok(Config::default())
        }
    }

    pub fn save(&self) -> Result<()> {
        let config_path = get_config_path()?;

        if let Some(parent) = config_path.parent() {
            fs::create_dir_all(parent)?;
        }

        let content = self.to_toml_with_comments()?;
        fs::write(&config_path, content)?;
        Ok(())
    }

    fn to_toml_with_comments(&self) -> Result<String> {
        let mut content = String::new();
        content.push_str("# Stax Configuration File\n");
        content.push_str("# This file is automatically generated but can be manually edited\n");
        content.push('\n');

        content.push_str("# Default base branch for new stacks\n");
        content.push_str(&format!(
            "default_base_branch = \"{}\"\n",
            self.default_base_branch
        ));
        content.push('\n');

        content.push_str("# Automatically push branches when creating PRs\n");
        content.push_str(&format!("auto_push = {}\n", self.auto_push));
        content.push('\n');

        content.push_str("# Create draft PRs by default\n");
        content.push_str(&format!("draft_prs = {}\n", self.draft_prs));
        content.push('\n');

        if let Some(template) = &self.pr_template {
            content.push_str("# Default PR template\n");
            content.push_str(&format!("pr_template = '''\n{template}\n\'''\n"));
            content.push('\n');
        }

        if !self.user_settings.is_empty() {
            content.push_str("# Custom user settings\n");
            content.push_str("[user_settings]\n");
            for (key, value) in &self.user_settings {
                content.push_str(&format!("{key} = \"{value}\"\n"));
            }
        }

        Ok(content)
    }

    pub fn set(&mut self, key: &str, value: &str) -> Result<()> {
        match key {
            "github_token" => {
                return Err(anyhow!(
                    "GitHub token is managed by 'stax auth', not config. Run 'stax auth login' to authenticate."
                ));
            }
            "default_base_branch" => self.default_base_branch = value.to_string(),
            "auto_push" => self.auto_push = value.parse()?,
            "draft_prs" => self.draft_prs = value.parse()?,
            "pr_template" => self.pr_template = Some(value.to_string()),
            _ => {
                self.user_settings
                    .insert(key.to_string(), value.to_string());
            }
        }
        Ok(())
    }

    pub fn get(&self, key: &str) -> Option<String> {
        match key {
            "default_base_branch" => Some(self.default_base_branch.clone()),
            "auto_push" => Some(self.auto_push.to_string()),
            "draft_prs" => Some(self.draft_prs.to_string()),
            "pr_template" => self.pr_template.clone(),
            _ => self.user_settings.get(key).cloned(),
        }
    }

    pub fn list(&self) -> HashMap<String, String> {
        let mut settings = HashMap::new();

        settings.insert(
            "default_base_branch".to_string(),
            self.default_base_branch.clone(),
        );
        settings.insert("auto_push".to_string(), self.auto_push.to_string());
        settings.insert("draft_prs".to_string(), self.draft_prs.to_string());

        if let Some(template) = &self.pr_template {
            settings.insert("pr_template".to_string(), template.clone());
        }

        for (key, value) in &self.user_settings {
            settings.insert(key.clone(), value.clone());
        }

        settings
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_config_default() {
        let config = Config::default();
        assert_eq!(config.default_base_branch, "main");
        assert!(config.auto_push);
        assert!(!config.draft_prs);
        assert!(config.pr_template.is_none());
        assert!(config.user_settings.is_empty());
    }

    #[test]
    fn test_config_set_and_get() {
        let mut config = Config::default();

        // Test setting various config values
        config.set("default_base_branch", "develop").unwrap();
        assert_eq!(config.default_base_branch, "develop");

        config.set("auto_push", "false").unwrap();
        assert!(!config.auto_push);

        config.set("draft_prs", "true").unwrap();
        assert!(config.draft_prs);

        config
            .set("pr_template", "## Summary\n\n## Testing")
            .unwrap();
        assert_eq!(
            config.pr_template,
            Some("## Summary\n\n## Testing".to_string())
        );

        config.set("custom_key", "custom_value").unwrap();
        assert_eq!(
            config.user_settings.get("custom_key"),
            Some(&"custom_value".to_string())
        );
    }

    #[test]
    fn test_config_list() {
        let mut config = Config::default();
        config.set("custom_setting", "test_value").unwrap();

        let settings = config.list();
        assert!(settings.contains_key("default_base_branch"));
        assert!(settings.contains_key("auto_push"));
        assert!(settings.contains_key("draft_prs"));
        assert!(settings.contains_key("custom_setting"));
        assert_eq!(
            settings.get("custom_setting"),
            Some(&"test_value".to_string())
        );
    }

    #[test]
    fn test_config_invalid_bool() {
        let mut config = Config::default();
        let result = config.set("auto_push", "invalid_bool");
        assert!(result.is_err());
    }

    #[test]
    fn test_toml_generation_with_comments() {
        let mut config = Config::default();
        config.default_base_branch = "develop".to_string();
        config.auto_push = false;
        config.pr_template = Some("## Summary\n\n## Testing".to_string());
        config
            .user_settings
            .insert("custom_key".to_string(), "custom_value".to_string());

        let toml_content = config.to_toml_with_comments().unwrap();

        // Check that comments are included
        assert!(toml_content.contains("# Stax Configuration File"));
        assert!(toml_content.contains("# Default base branch for new stacks"));
        assert!(toml_content.contains("# Automatically push branches"));

        // Check that values are correct
        assert!(toml_content.contains("default_base_branch = \"develop\""));
        assert!(toml_content.contains("auto_push = false"));
        assert!(toml_content.contains("pr_template = '''"));
        assert!(toml_content.contains("[user_settings]"));
        assert!(toml_content.contains("custom_key = \"custom_value\""));
    }

    #[test]
    fn test_config_path_resolution() {
        // Test that config path resolution doesn't panic
        let result = get_config_path();
        assert!(result.is_ok());

        let path = result.unwrap();
        assert!(path.to_string_lossy().contains("stax"));
        assert!(path.to_string_lossy().ends_with("config.toml"));
    }

    #[test]
    fn test_preferred_config_dir() {
        let result = get_preferred_config_dir();
        assert!(result.is_ok());

        let dir = result.unwrap();
        // Should contain config directory appropriate for the platform
        let dir_str = dir.to_string_lossy();

        #[cfg(target_os = "windows")]
        assert!(dir_str.contains("AppData"));

        #[cfg(not(target_os = "windows"))]
        assert!(dir_str.contains(".config"));
    }
}

fn get_config_path() -> Result<PathBuf> {
    let config_dir = get_preferred_config_dir()?;
    Ok(config_dir.join("stax").join("config.toml"))
}

fn get_preferred_config_dir() -> Result<PathBuf> {
    // On macOS and Linux, prefer ~/.config for CLI tools (following XDG spec)
    // On Windows, use the standard config directory
    #[cfg(not(target_os = "windows"))]
    {
        if let Some(home_dir) = dirs::home_dir() {
            let xdg_config = home_dir.join(".config");
            return Ok(xdg_config);
        }
    }

    // Fallback to system config directory
    dirs::config_dir().ok_or_else(|| anyhow!("Could not determine config directory"))
}

pub mod commands {
    use super::*;
    use crate::utils;

    pub async fn set(key: &str, value: &str) -> Result<()> {
        let mut config = Config::load()?;
        config.set(key, value)?;
        config.save()?;
        utils::print_success(&format!("Set {key} = {value}"));
        Ok(())
    }

    pub async fn get(key: &str) -> Result<()> {
        let config = Config::load()?;
        if let Some(value) = config.get(key) {
            println!("{value}");
        } else {
            utils::print_error(&format!("Configuration key '{key}' not found"));
        }
        Ok(())
    }

    pub async fn list() -> Result<()> {
        let config_path = get_config_path()?;
        let config = Config::load()?;
        let settings = config.list();

        // Always show the config file location
        println!("Configuration file: {}", config_path.display());
        println!();

        if settings.is_empty() {
            utils::print_info("No configuration set");
            return Ok(());
        }

        println!("Configuration:");
        for (key, value) in settings {
            println!("  {key} = {value}");
        }
        Ok(())
    }
}
